### ISSUE TITLE
Test reports not showing after running tests

### ISSUE THREAD

**Issue by akaroml** [OpenLiberty/liberty-dev-vscode-ext#20]
Repro steps:

1. Go to Liberty Dev Dashboard
2. Pick one service and Start
3. After service is started, right-click and "Run tests"
4. After tests finishes, right-click and "View integration test report" / "View unit test report"
![image](https://user-images.githubusercontent.com/16755094/69846924-8bf73700-12b0-11ea-9b63-7d7b78293470.png)

5. "Test report does not exist" was not showing
![image](https://user-images.githubusercontent.com/16755094/69846938-94e80880-12b0-11ea-9418-ab2bdf39e98d.png)

Expected result

1. Test reports should be presented

**Comment by kathrynkodama** [comment]
The "Test report does not exist" appears because it does not look like there were any tests in that project.  If tests exist the output looks similar to this:

![image](https://user-images.githubusercontent.com/26146482/69874898-2e4ff400-128a-11ea-9af7-fa8869226b8b.png)

Opening the test report then looks like this:
![image](https://user-images.githubusercontent.com/26146482/69874930-3d36a680-128a-11ea-8e05-bcb7965b3cfc.png)

The test report will only open if tests are run.

**Comment by akaroml** [comment]
Thanks for the explanation. The report will only be generated when there is at least 1 test case.

**Comment by kathrynkodama** [comment]
Fixed with #21. Issue #22 opened for future enhancements.
