### ISSUE TITLE
Better validation for custom dev-mode parameters

### ISSUE THREAD

**Issue by bensonnw** [OpenLiberty/liberty-dev-vscode-ext#50]
Current code is only checking the command starts with "-", since dev-model supports multiple parameters, we should verify each of them. 
- [ ] Maven starts with `-D`, Gradle starts with `--`
- [ ] Parameters separated by a space
- [ ] Check each parameter is in the support list. (https://github.com/OpenLiberty/ci.gradle/blob/master/docs/libertyDev.md)

**Comment by ericglau** [comment]
Perhaps we should only do the first item (`Maven starts with -D, Gradle starts with --`).  

For `Parameters separated by a space`, I'm not sure whether it is possible to check (if we don't do the third item) since you wouldn't know when the first param ends and when the second begins.

For `Check each parameter is in the support list.`, we may not want to do this, otherwise we will have to update that list whenever we add parameters in dev mode.  And, the user should be allowed to add parameters that are not dev mode related, such as other Maven or Gradle options like -e or -X or --debug or --stacktrace etc.

**Comment by bensonnw** [comment]
Tried the dev-mode command line, it has more options than this list (https://github.com/OpenLiberty/ci.gradle/blob/master/docs/libertyDev.md). and if we allow all of them to be specified, then this issue won't be valid
